// src/components/Payslip.jsx
import jsPDF from "jspdf";
import "jspdf-autotable"; // ✅ for table formatting
import "./Payslip.css";

export default function Payslip({ employee }) {
  const netPay = employee.salary - employee.deductions;

  function downloadPDF() {
    const doc = new jsPDF();

    // Title
    doc.setFontSize(18);
    doc.text(`Payslip for ${employee.name}`, 14, 20);

    // Table with icons
    doc.autoTable({
      startY: 30,
      head: [["Detail", "Value"]],
      body: [
        ["\uf0f2 Employee ID", employee.id],          // Font Awesome briefcase
        ["\uf155 Base Salary", `$${employee.salary}`], // Font Awesome dollar-sign
        ["\uf068 Deductions", `$${employee.deductions}`], // Font Awesome minus
        ["\uf00c Net Pay", `$${netPay}`],             // Font Awesome check
      ],
      styles: { font: "helvetica", fontSize: 12 },
      headStyles: { fillColor: [30, 42, 56], textColor: [255, 255, 255] },
      bodyStyles: { fillColor: [249, 249, 249] },
      alternateRowStyles: { fillColor: [255, 255, 255] },
    });

    // Footer
    doc.setFontSize(10);
    doc.text("Generated by Payroll Management System", 14, doc.internal.pageSize.height - 10);

    doc.save(`payslip_${employee.id}.pdf`);
  }

  return (
    <div className="payslip">
      <h3 className="payslip-title">Payslip for {employee.name}</h3>
      <table className="payslip-table">
        <tbody>
          <tr>
            <td><i className="fas fa-briefcase"></i> Employee ID</td>
            <td>{employee.id}</td>
          </tr>
          <tr>
            <td><i className="fas fa-dollar-sign"></i> Base Salary</td>
            <td>${employee.salary}</td>
          </tr>
          <tr>
            <td><i className="fas fa-minus"></i> Deductions</td>
            <td>${employee.deductions}</td>
          </tr>
          <tr className="netpay-row">
            <td><i className="fas fa-check"></i> Net Pay</td>
            <td>${netPay}</td>
          </tr>
        </tbody>
      </table>
      <button className="btn" onClick={downloadPDF}>Download PDF</button>
    </div>
  );
}
