version: "3.9"

services:
  backend:
    build:
      context: ./Payroll_Web_App.Server
      dockerfile: Dockerfile
    container_name: payroll_api
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ConnectionStrings__DefaultConnection=Server=Server=sql.toncom159.com;Database=Payroll_DB;User Id=Guest;Password=StrongPassword123!;Encrypt=False;TrustServerCertificate=True;
    ports:
      - "5000:8080"
    networks:
      - payroll_net

  frontend:
    build:
      context: ./payroll_web_app.client
      dockerfile: Dockerfile
    container_name: payroll_client
    ports:
      - "5173:80"
    depends_on:
      - backend
    networks:
      - payroll_net

networks:
  payroll_net:
